### PR TITLE
Add minimal snapshot handling support

### PR DESCRIPTION
**Pull request by mexicarne**
Create snapshot example:
```python
>>> import libzfs
>>> import nvpair
>>> zfs = libzfs.ZFS()
>>> ds = zfs.get_dataset('zroot/ROOT/default')
>>> nv = nvpair.NVList()
>>> ds.snapshot('zroot/ROOT/default@jojo', nv)
```

Destroy snapshot example:
```python
>>> import libzfs
>>> zfs = libzfs.ZFS()
>>> ds = zfs.get_dataset('zroot/ROOT/default')
>>> ds.destroy_snapshot('jojo')
```

### CODE REVIEW

**Comment by jceel** [comment]
Thank you :) However, shouldn't "destroy_snaps" be "destroy_snapshot"?

**Comment by mexicarne** [comment]
Yes, it would be better for sure :). How can I fix this now (in github terms)?

**Comment by jceel** [comment]
Don't worry about it, I'll fix it once it will be merged.

**Comment by bapt** [comment]
Any schedule for merging this feature? I really need it :)

**Comment by jceel** [comment]
Done. Sorry that you needed to wait so long, I was struggling with git repos synchronization (that repo is backed by internal iXsystems git server and github synchronization needs to work either way to allow people contributing ;)

**Pull request merged**
